{
  "hash": "cfb00437674d29a6a5ca8b5900cb19d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"03. MCMC basics\"\n---\n\n::: {.callout-note appearance=\"minimal\" icon=false}\nLanguage: **R** (Quarto) - [Python version](python.ipynb)\n:::\n\nPorted from\n[`03_mcmc_basics.ipynb`](https://github.com/USACE-RMC/Numerics-Python-Examples/blob/main/notebooks/03_mcmc_basics.ipynb)\nin the USACE-RMC Numerics-Python-Examples repository (0BSD licensed). The upstream\nnotebook drives the C# `Numerics.dll` through pythonnet; this version uses\n`corehydror`, whose compiled core is a validated C++ port of the same library. The\nseeded data draws below reproduce the upstream values exactly. The posterior numbers\nare close to the upstream's but deliberately not identical, because this port builds\nits priors differently (explained below). The Python version of this example uses\nthe same core and prints the same numbers.\n\nOne honest caveat up front: the upstream's first example estimates the mean alone,\nwith the standard deviation fixed at 15 and a hand-picked Uniform(50, 150) prior\npassed through a custom log-likelihood delegate. `mcmc_sample()` always fits every\nparameter of a family under uniform priors derived from the family's parameter\nconstraints, so that fixed-sigma example is not expressible with the public API.\nThis port teaches the same concepts on the upstream's second example, where both\nthe mean and the standard deviation are unknown.\n\n## What you'll learn\n\n- What MCMC is and when to use it.\n- How the Random Walk Metropolis-Hastings (RWMH) sampler works.\n- How to read a trace plot and spot a run that has not converged.\n- What warmup (burn-in) and thinning do.\n- How to summarize a posterior and check acceptance rates and R-hat.\n\n## What is MCMC\n\nMarkov Chain Monte Carlo draws samples from a posterior distribution that is known\nonly up to a normalizing constant. By Bayes' theorem, the posterior is proportional\nto the product of the prior and the likelihood:\n\n$$\n\\pi(\\theta \\mid y) \\propto \\pi(\\theta) \\cdot L(y \\mid \\theta)\n$$\n\nIt is common to work with the logarithm of this product, which is how the library\nworks internally:\n\n$$\n\\log \\pi(\\theta \\mid y) = \\log \\pi(\\theta) + \\log L(y \\mid \\theta) + \\text{const}\n$$\n\nMCMC is useful when:\n\n- You want to quantify uncertainty in parameters, not just point estimates.\n- You have prior knowledge to incorporate.\n- You need full posterior distributions.\n- Standard optimization methods are insufficient.\n\nThe library ports all of the upstream samplers; `mcmc_sample()` accepts any of them\nby name:\n\n| Sampler | Full name | Best for |\n|---------|-----------|----------|\n| RWMH | Random Walk Metropolis-Hastings | General purpose, small dimensions |\n| ARWMH | Adaptive RWMH | Medium dimensions (2-20) |\n| DEMCz | Differential Evolution MCMC | High dimensions, multimodal |\n| DEMCzs | DE-MCMC with snooker update | Very high dimensions |\n| HMC | Hamiltonian Monte Carlo | Smooth posteriors |\n| NUTS | No-U-Turn Sampler | General smooth posteriors |\n| SNIS | Self-normalized importance sampling | Cheap approximate posteriors |\n\nThis example uses RWMH, the simplest and most robust baseline. At each iteration\nit proposes a new state from a symmetric normal distribution centered at the\ncurrent state, $\\theta^* \\sim \\mathcal{N}(\\theta, \\Sigma)$, and accepts it with\nprobability\n\n$$\n\\alpha = \\min\\left(1, \\frac{\\pi(\\theta^*)}{\\pi(\\theta)}\\right),\n$$\n\ncomputed in log space as $\\log \\alpha = \\log \\pi(\\theta^*) - \\log \\pi(\\theta)$.\nProposals that fall outside the prior bounds are rejected without evaluating the\nlikelihood. Theory gives target acceptance rates for RWMH of about 44% for one\nparameter, falling toward 23.4% in high dimensions (Roberts, Gelman, and Gilks,\n1997); we will check ours against that below.\n\n## Setup\n\nThe upstream setup loads the CoreCLR runtime, resolves the DLL, and builds .NET\n`List` and `Array` objects. None of that exists here; plain numeric vectors work\neverywhere.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corehydror)\n\n# Earth-tone palette used throughout, one color per chain\npal <- c(\"#6b7f3f\", \"#b06a3b\", \"#5b7a8c\", \"#8c8c7a\")\n```\n:::\n\n\n## Step 1: Generate synthetic data\n\nWe draw 50 observations from a Normal(100, 15) with seed 42, exactly the upstream's\n`Normal(100, 15).GenerateRandomValues(50, 42)`. The port keeps the C# Mersenne\nTwister bit-exact, so these are the same 50 numbers the upstream notebook sees:\nthe sample mean prints 96.40 and the population standard deviation prints 17.13,\nmatching the upstream output digit for digit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrue_mu <- 100\ntrue_sigma <- 15\ndata <- dist_random(distribution(\"Normal\", c(true_mu, true_sigma)), 50, seed = 42)\npop_sd <- sqrt(mean((data - mean(data))^2))\n\ncat(\"Generated\", length(data), \"observations\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerated 50 observations\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Sample mean: %.2f\\n\", mean(data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample mean: 96.40\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Sample std: %.2f\\n\", pop_sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample std: 17.13\n```\n\n\n:::\n\n```{.r .cell-code}\nhist(data, breaks = 15, col = \"#6b7f3f\", border = \"white\",\n     main = \"Observed data\", xlab = \"Value\")\nabline(v = mean(data), col = \"#b06a3b\", lty = 2, lwd = 2)\nlegend(\"topright\", legend = sprintf(\"Sample mean = %.1f\", mean(data)),\n       col = \"#b06a3b\", lty = 2, lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Step 2: Priors and likelihood\n\nThe upstream builds a .NET `List` of prior distributions (Uniform(50, 150) for the\nmean, Uniform(1, 50) for the standard deviation) and wraps a Python function as a\n`LogLikelihood` delegate. Here `mcmc_sample()` assembles both pieces for you: the\nlog-likelihood is the family's own, evaluated in the compiled core, and the priors\nare uniforms spanning the family's parameter constraints (the C#\n`GetParameterConstraints` bounds, which scale with the data). For this sample they\nwork out to mu ~ Uniform(-1000, 1000) and sigma ~ Uniform(~0, 1000). Both prior\nsets are effectively flat over the region where the likelihood has any mass, so the\nposteriors come out nearly the same, but the numbers cannot match the upstream's\nbit for bit.\n\n## Step 3: A first run, badly initialized\n\nBy default the sampler runs 4 chains initialized at the maximum a posteriori (MAP)\nestimate. To see why convergence checking matters, we first do the opposite:\ninitialize each chain at a random draw from the (very wide) priors and run only\n1,000 iterations.\n\nA trace plot shows a parameter's sampled value at each recorded iteration, one line\nper chain. A healthy, well-mixed chain looks like a fluffy caterpillar: random\nscribble centered on the posterior mean, with no visible trends and all chains\noverlapping. Chains that drift, or that disagree with each other, have not\nconverged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbad <- mcmc_sample(data, \"Normal\", sampler = \"RWMH\",\n                   iterations = 1000, warmup = 500, thinning = 1,\n                   seed = 12345, initialize = \"Randomize\")\n\nbad_mu <- sapply(bad$chains, \\(chain) chain[, 1])\nmatplot(bad_mu, type = \"l\", lty = 1, lwd = 0.6, col = pal,\n        xlab = \"Iteration\", ylab = \"mu\",\n        main = \"Trace plot: randomized starts, too few iterations\")\nabline(v = 500, col = \"black\", lty = 2)\nlegend(\"topright\", legend = c(paste(\"chain\", 1:4), \"warmup cutoff\"),\n       col = c(pal, \"black\"), lty = c(1, 1, 1, 1, 2), lwd = 1, bty = \"n\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncat(\"R-hat:\", round(bad$rhat, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR-hat: 2.641 1.976 \n```\n\n\n:::\n:::\n\n\nThe chains start scattered across the prior and spend most of the run wandering\ntoward the posterior. The Gelman-Rubin statistic (R-hat) compares within-chain and\nbetween-chain variance and should be very close to 1 at convergence; values well\nabove 1, like these, flag a run whose chains are still exploring. The fix is\ncheap: better initialization and more iterations.\n\n## Step 4: A proper run\n\nNow the default MAP initialization and 3,000 iterations per chain, with the first\n1,500 treated as warmup. The chains in the result include the warmup segment,\nwhich is what makes plots like this possible; R-hat is computed from the\npost-warmup portion only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- mcmc_sample(data, \"Normal\", sampler = \"RWMH\",\n                   iterations = 3000, warmup = 1500, thinning = 1, seed = 12345)\nwarmup <- 1500\n\nop <- par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))\nfor (p in 1:2) {\n  traces <- sapply(fit$chains, \\(chain) chain[, p])\n  matplot(traces, type = \"l\", lty = 1, lwd = 0.4, col = pal,\n          xlab = \"Iteration\", ylab = c(\"mu\", \"sigma\")[p],\n          main = if (p == 1) \"Trace plots (dashed line = warmup cutoff)\" else \"\")\n  abline(v = warmup, col = \"black\", lty = 2)\n}\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n\ncat(\"R-hat:\", round(fit$rhat, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR-hat: 1.005 1.003 \n```\n\n\n:::\n:::\n\n\nBoth parameters now show the fluffy caterpillar: four overlapping chains, no\ntrends, and R-hat within a hair of 1.\n\n## Step 5: Posterior summaries\n\nThe result carries per-parameter posterior summaries. Following the C# design,\nthese are computed from a dedicated posterior sample of about 10,000 draws that\nthe sampler records after the main iterations, so they do not depend on exactly\nwhere you cut the warmup. The credible interval is the central 90% (5th to 95th\npercentile). Recall the true values are mu = 100 and sigma = 15, and the data\nsummaries are 96.40 and 17.31 (sample standard deviation).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_df <- data.frame(\n  parameter = fit$parameters,\n  true = c(true_mu, true_sigma),\n  map = fit$map,\n  post_mean = fit$posterior_mean,\n  post_sd = fit$posterior_sd,\n  median = fit$posterior_median,\n  pct_5 = fit$posterior_lower_ci,\n  pct_95 = fit$posterior_upper_ci,\n  rhat = fit$rhat,\n  ess = fit$ess\n)\nsummary_df[-1] <- round(summary_df[-1], 4)\nprint(summary_df, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n parameter true     map post_mean post_sd  median   pct_5   pct_95   rhat\n         µ  100 96.3987   96.4027  2.4468 96.4842 92.3519 100.2315 1.0052\n         σ   15 17.1323   17.7938  1.8559 17.6358 15.0499  21.1403 1.0031\n      ess\n 1482.406\n 1065.802\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nAcceptance rates by chain:\", round(fit$acceptance_rates, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAcceptance rates by chain: 0.441 0.43 0.441 0.435 \n```\n\n\n:::\n:::\n\n\nThe posterior mean of mu sits on the sample mean, and the 90% credible interval\ncomfortably covers the true value of 100. The posterior for sigma centers near the\nsample standard deviation of 17.3 rather than the true 15: with 50 observations\nthis particular seed simply drew a wide sample, and the upstream notebook sees the\nidentical effect with its own priors (its sigma interval is [15.02, 21.02]; ours is\n[15.05, 21.14]). The data, not the method, set that limit.\n\nThe acceptance rates land right around 0.44. For a two-parameter RWMH that is\nsquarely in the healthy range between the one-dimensional optimum (44%) and the\nhigh-dimensional limit (23.4%). Very low rates mean the proposals are too\naggressive and almost always rejected; very high rates mean timid proposals and\nslow exploration.\n\nThe marginal posteriors and the joint posterior, from the pooled post-warmup\ndraws:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost <- do.call(rbind, lapply(fit$chains, \\(chain) chain[-seq_len(warmup), ]))\n\nop <- par(mfrow = c(1, 2), mar = c(4, 4, 2, 1))\nfor (p in 1:2) {\n  hist(post[, p], breaks = 40, freq = FALSE, col = \"#6b7f3f\", border = \"white\",\n       main = paste(\"Posterior:\", c(\"mu\", \"sigma\")[p]),\n       xlab = c(\"mu\", \"sigma\")[p])\n  abline(v = fit$posterior_mean[p], col = \"#b06a3b\", lty = 2, lwd = 2)\n}\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n\nplot(post[, 1], post[, 2], pch = 16, cex = 0.3,\n     col = adjustcolor(\"#5b7a8c\", alpha.f = 0.15),\n     xlab = \"mu\", ylab = \"sigma\", main = \"Joint posterior\")\npoints(true_mu, true_sigma, pch = 8, cex = 2, lwd = 2, col = \"#b06a3b\")\nlegend(\"topright\", legend = \"True value\", pch = 8, col = \"#b06a3b\", bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n:::\n\n\n## Understanding warmup and thinning\n\n**Warmup (burn-in).** The first stretch of every chain is influenced by its\narbitrary starting point, as the randomized run above made obvious. Those samples\nare misleading and should be discarded. Rules of thumb from the upstream notebook:\nRWMH wants 2,000-5,000 warmup iterations on hard problems, gradient samplers\n(HMC/NUTS) closer to 1,000-2,000, and warmup of about half the iterations is a\nreasonable default. This port enforces the C# constraint that warmup cannot exceed\nhalf the iterations. Note the division of labor in the results: `chains` keeps the\nwarmup segment so you can plot it, R-hat drops it, and the posterior summaries come\nfrom the separate post-run sample described above.\n\n**Thinning.** Successive MCMC samples are autocorrelated. Thinning records only\nevery nth state: each row of a chain is the state after `thinning` internal steps,\nand the default interval in this library is 20, matching C#. We set `thinning = 1`\nin this example precisely so the raw autocorrelation is visible below. Thinning\nreduces autocorrelation in what you store, but it does not add information; running\nlonger is always at least as good. Keep the interval at or below the\nautocorrelation length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(post[, 1], lag.max = 50, main = \"Autocorrelation of mu (post-warmup, thinning = 1)\",\n    col = \"#6b7f3f\")\n```\n\n::: {.cell-output-display}\n![](r_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe autocorrelation decays within a few dozen lags, which is typical of a healthy\nrandom-walk sampler. The effective sample size in the summary table (about 1,500\nfor mu out of 10,000 posterior draws) tells the same story: RWMH explores by\ndiffusion, so its draws are far from independent, and gradient samplers would score\nmuch higher here.\n\n## Summary\n\nIn this notebook you:\n\n- Built a Bayesian model for Normal data with unknown mean and standard deviation.\n- Ran RWMH through `mcmc_sample()`, which supplies constraint-based uniform priors\n  and the family's own log-likelihood.\n- Diagnosed a bad run and a good one with trace plots and R-hat.\n- Read posterior summaries, credible intervals, acceptance rates, and ESS.\n\nKey takeaway: MCMC gives full uncertainty quantification for parameters, not only\npoint estimates.\n\n## Reproduction check\n\nThe seeded data draw is bit-exact against the upstream C# stream. The posterior\ncannot be compared bit for bit: the upstream uses hand-picked Uniform(50, 150) and\nUniform(1, 50) priors through a custom likelihood delegate, while `mcmc_sample()`\nuses the family's constraint-based uniform priors, so the samplers consume\ndifferent random streams. Those rows are checked statistically. The final rows\nassert cross-language identity: the Python twin asserts the very same literals,\nbecause both packages run the same compiled core with the same seed.\n\n| Quantity | Upstream C# | This port | Status |\n|----------|------------:|----------:|--------|\n| Seeded sample mean, `GenerateRandomValues(50, 42)` | 96.40 | 96.40 | exact |\n| Seeded sample std (population) | 17.13 | 17.13 | exact |\n| Posterior mean of mu | 96.427 | 96.403 | statistical (priors differ) |\n| 90% CI for mu covers true mu = 100 | [92.22, 100.54] | [92.35, 100.23] | statistical |\n| 90% CI for sigma covers sample sd 17.31 | [15.02, 21.02] | [15.05, 21.14] | statistical |\n| RWMH acceptance rate near 0.44 | 0.43 | 0.43-0.44 | statistical |\n| First seeded data value | n/a | 95.20221411105254 | exact (R == Python) |\n| Posterior means (mu, sigma) | n/a | shared literals | exact (R == Python) |\n\nThe chunk below fails the render if any check drifts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Upstream: 03_mcmc_basics.ipynb, cell 5 output (seeded data),\n# cell 19 output (two-parameter posterior table), cell 21 output (acceptance rate).\n\n# Exact tier: the seeded data draw reproduces the C# Mersenne Twister stream.\nstopifnot(\n  round(mean(data), 2) == 96.40,\n  round(pop_sd, 2) == 17.13\n)\n\n# Statistical tier: constraint-based priors differ from the upstream's hand-picked\n# ones, so we assert the inference, not the draws.\nstopifnot(\n  abs(fit$posterior_mean[1] - mean(data)) < 1.0,\n  fit$posterior_lower_ci[1] <= true_mu, true_mu <= fit$posterior_upper_ci[1],\n  fit$posterior_lower_ci[2] <= sd(data), sd(data) <= fit$posterior_upper_ci[2],\n  all(fit$rhat < 1.05),\n  all(fit$acceptance_rates > 0.2 & fit$acceptance_rates < 0.6),\n  max(bad$rhat) > 1.5 # the badly initialized run is flagged\n)\n\n# Exact tier, cross-language: the Python twin asserts these same literals. The\n# values are bit-exact across R, Python, and the C# library; the comparisons carry\n# a 1e-15 relative tolerance only because R's decimal parser can land one ulp away\n# from the written literal.\nstopifnot(\n  abs(data[1] / 95.20221411105254 - 1) < 1e-15,\n  abs(fit$posterior_mean[1] / 96.40267301325859 - 1) < 1e-15,\n  abs(fit$posterior_mean[2] / 17.793754146622998 - 1) < 1e-15,\n  abs(fit$acceptance_rates[1] / 0.4410909090909091 - 1) < 1e-15\n)\ncat(\"All reproduction checks passed.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll reproduction checks passed.\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}