# Generated by cpp11: do not edit by hand

bf_dist_moments_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_moments_`, target, params)
}

bf_dist_pdf_ <- function(target, params, x) {
  .Call(`_bestfitr_bf_dist_pdf_`, target, params, x)
}

bf_dist_cdf_ <- function(target, params, x) {
  .Call(`_bestfitr_bf_dist_cdf_`, target, params, x)
}

bf_dist_quantile_ <- function(target, params, p) {
  .Call(`_bestfitr_bf_dist_quantile_`, target, params, p)
}

bf_dist_valid_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_valid_`, target, params)
}

bf_dist_fit_ <- function(target, data, method) {
  .Call(`_bestfitr_bf_dist_fit_`, target, data, method)
}

bf_dist_linear_moments_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_linear_moments_`, target, params)
}

bf_gev_pdf_ <- function(x, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_pdf_`, x, location, scale, shape)
}

bf_gev_cdf_ <- function(x, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_cdf_`, x, location, scale, shape)
}

bf_gev_quantile_ <- function(p, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_quantile_`, p, location, scale, shape)
}

bf_gev_moments_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_moments_`, location, scale, shape)
}

bf_gev_valid_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_valid_`, location, scale, shape)
}

bf_gev_fit_ <- function(data, method) {
  .Call(`_bestfitr_bf_gev_fit_`, data, method)
}

bf_gev_quantile_variance_ <- function(p, location, scale, shape, sample_size) {
  .Call(`_bestfitr_bf_gev_quantile_variance_`, p, location, scale, shape, sample_size)
}

bf_gev_linear_moments_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_linear_moments_`, location, scale, shape)
}

bf_gev_quantile_gradient_ <- function(p, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_quantile_gradient_`, p, location, scale, shape)
}

bf_gev_parameter_covariance_ <- function(location, scale, shape, sample_size) {
  .Call(`_bestfitr_bf_gev_parameter_covariance_`, location, scale, shape, sample_size)
}
