# Generated by cpp11: do not edit by hand

bf_bootstrap_run_ <- function(model, mu, sigma, sample_size, probabilities, dataset, replicates, seed, max_retries, run, ci_method, alpha) {
  .Call(`_bestfitr_bf_bootstrap_run_`, model, mu, sigma, sample_size, probabilities, dataset, replicates, seed, max_retries, run, ci_method, alpha)
}

bf_cop_val_ <- function(type, params, method, args, marg_x_target, marg_x_params, marg_y_target, marg_y_params) {
  .Call(`_bestfitr_bf_cop_val_`, type, params, method, args, marg_x_target, marg_x_params, marg_y_target, marg_y_params)
}

bf_cop_fit_ <- function(type, x, y, method, marg_x, marg_y) {
  .Call(`_bestfitr_bf_cop_fit_`, type, x, y, method, marg_x, marg_y)
}

bf_dist_moments_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_moments_`, target, params)
}

bf_dist_pdf_ <- function(target, params, x) {
  .Call(`_bestfitr_bf_dist_pdf_`, target, params, x)
}

bf_dist_cdf_ <- function(target, params, x) {
  .Call(`_bestfitr_bf_dist_cdf_`, target, params, x)
}

bf_dist_quantile_ <- function(target, params, p) {
  .Call(`_bestfitr_bf_dist_quantile_`, target, params, p)
}

bf_dist_valid_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_valid_`, target, params)
}

bf_dist_fit_ <- function(target, data, method) {
  .Call(`_bestfitr_bf_dist_fit_`, target, data, method)
}

bf_dist_linear_moments_ <- function(target, params) {
  .Call(`_bestfitr_bf_dist_linear_moments_`, target, params)
}

bf_trunc_moments_ <- function(base_target, base_params, lo, hi) {
  .Call(`_bestfitr_bf_trunc_moments_`, base_target, base_params, lo, hi)
}

bf_trunc_pdf_ <- function(base_target, base_params, lo, hi, x) {
  .Call(`_bestfitr_bf_trunc_pdf_`, base_target, base_params, lo, hi, x)
}

bf_trunc_cdf_ <- function(base_target, base_params, lo, hi, x) {
  .Call(`_bestfitr_bf_trunc_cdf_`, base_target, base_params, lo, hi, x)
}

bf_trunc_quantile_ <- function(base_target, base_params, lo, hi, p) {
  .Call(`_bestfitr_bf_trunc_quantile_`, base_target, base_params, lo, hi, p)
}

bf_trunc_valid_ <- function(base_target, base_params, lo, hi) {
  .Call(`_bestfitr_bf_trunc_valid_`, base_target, base_params, lo, hi)
}

bf_emp_moments_ <- function(x_vals, p_vals, p_transform) {
  .Call(`_bestfitr_bf_emp_moments_`, x_vals, p_vals, p_transform)
}

bf_emp_pdf_ <- function(x_vals, p_vals, p_transform, x) {
  .Call(`_bestfitr_bf_emp_pdf_`, x_vals, p_vals, p_transform, x)
}

bf_emp_cdf_ <- function(x_vals, p_vals, p_transform, x) {
  .Call(`_bestfitr_bf_emp_cdf_`, x_vals, p_vals, p_transform, x)
}

bf_emp_quantile_ <- function(x_vals, p_vals, p_transform, prob) {
  .Call(`_bestfitr_bf_emp_quantile_`, x_vals, p_vals, p_transform, prob)
}

bf_emp_valid_ <- function(x_vals, p_vals, p_transform) {
  .Call(`_bestfitr_bf_emp_valid_`, x_vals, p_vals, p_transform)
}

bf_kde_moments_ <- function(data, kernel, bandwidth, bounded_by_data) {
  .Call(`_bestfitr_bf_kde_moments_`, data, kernel, bandwidth, bounded_by_data)
}

bf_kde_pdf_ <- function(data, kernel, bandwidth, bounded_by_data, x) {
  .Call(`_bestfitr_bf_kde_pdf_`, data, kernel, bandwidth, bounded_by_data, x)
}

bf_kde_cdf_ <- function(data, kernel, bandwidth, bounded_by_data, x) {
  .Call(`_bestfitr_bf_kde_cdf_`, data, kernel, bandwidth, bounded_by_data, x)
}

bf_kde_quantile_ <- function(data, kernel, bandwidth, bounded_by_data, prob) {
  .Call(`_bestfitr_bf_kde_quantile_`, data, kernel, bandwidth, bounded_by_data, prob)
}

bf_kde_valid_ <- function(data, kernel, bandwidth, bounded_by_data) {
  .Call(`_bestfitr_bf_kde_valid_`, data, kernel, bandwidth, bounded_by_data)
}

bf_mix_moments_ <- function(comp_targets, comp_params_list, weights) {
  .Call(`_bestfitr_bf_mix_moments_`, comp_targets, comp_params_list, weights)
}

bf_mix_pdf_ <- function(comp_targets, comp_params_list, weights, x) {
  .Call(`_bestfitr_bf_mix_pdf_`, comp_targets, comp_params_list, weights, x)
}

bf_mix_cdf_ <- function(comp_targets, comp_params_list, weights, x) {
  .Call(`_bestfitr_bf_mix_cdf_`, comp_targets, comp_params_list, weights, x)
}

bf_mix_quantile_ <- function(comp_targets, comp_params_list, weights, prob) {
  .Call(`_bestfitr_bf_mix_quantile_`, comp_targets, comp_params_list, weights, prob)
}

bf_mix_valid_ <- function(comp_targets, comp_params_list, weights) {
  .Call(`_bestfitr_bf_mix_valid_`, comp_targets, comp_params_list, weights)
}

bf_cr_moments_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation) {
  .Call(`_bestfitr_bf_cr_moments_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation)
}

bf_cr_pdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_bestfitr_bf_cr_pdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

bf_cr_log_pdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_bestfitr_bf_cr_log_pdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

bf_cr_cdf_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x) {
  .Call(`_bestfitr_bf_cr_cdf_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, x)
}

bf_cr_quantile_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, prob) {
  .Call(`_bestfitr_bf_cr_quantile_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation, prob)
}

bf_cr_valid_ <- function(comp_targets, comp_params_list, minimum_of_rv, dependency, correlation) {
  .Call(`_bestfitr_bf_cr_valid_`, comp_targets, comp_params_list, minimum_of_rv, dependency, correlation)
}

bf_estimation_run_ <- function(target, model_json, dataset, optimizer, sample_size, seed) {
  .Call(`_bestfitr_bf_estimation_run_`, target, model_json, dataset, optimizer, sample_size, seed)
}

bf_estimation_bic_ <- function(target, model_json, dataset, optimizer, n) {
  .Call(`_bestfitr_bf_estimation_bic_`, target, model_json, dataset, optimizer, n)
}

bf_estimation_bayes_run_ <- function(model_json, dataset, sampler, seed, iterations, warmup_iterations, number_of_chains, thinning_interval, initial_iterations, output_length) {
  .Call(`_bestfitr_bf_estimation_bayes_run_`, model_json, dataset, sampler, seed, iterations, warmup_iterations, number_of_chains, thinning_interval, initial_iterations, output_length)
}

bf_model_data_frame_ <- function(model_json, dataset) {
  .Call(`_bestfitr_bf_model_data_frame_`, model_json, dataset)
}

bf_model_simulate_ <- function(model_json, dataset, sample_size, seed) {
  .Call(`_bestfitr_bf_model_simulate_`, model_json, dataset, sample_size, seed)
}

bf_estimation_gmm_run_ <- function(model_json, dataset, strategy, optimizer, max_gmm_iterations, sample_size, seed) {
  .Call(`_bestfitr_bf_estimation_gmm_run_`, model_json, dataset, strategy, optimizer, max_gmm_iterations, sample_size, seed)
}

bf_estimation_gmm_qvar_ <- function(model_json, dataset, strategy, optimizer, max_gmm_iterations, aep) {
  .Call(`_bestfitr_bf_estimation_gmm_qvar_`, model_json, dataset, strategy, optimizer, max_gmm_iterations, aep)
}

bf_gev_pdf_ <- function(x, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_pdf_`, x, location, scale, shape)
}

bf_gev_cdf_ <- function(x, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_cdf_`, x, location, scale, shape)
}

bf_gev_quantile_ <- function(p, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_quantile_`, p, location, scale, shape)
}

bf_gev_moments_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_moments_`, location, scale, shape)
}

bf_gev_valid_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_valid_`, location, scale, shape)
}

bf_gev_fit_ <- function(data, method) {
  .Call(`_bestfitr_bf_gev_fit_`, data, method)
}

bf_gev_quantile_variance_ <- function(p, location, scale, shape, sample_size) {
  .Call(`_bestfitr_bf_gev_quantile_variance_`, p, location, scale, shape, sample_size)
}

bf_gev_linear_moments_ <- function(location, scale, shape) {
  .Call(`_bestfitr_bf_gev_linear_moments_`, location, scale, shape)
}

bf_gev_quantile_gradient_ <- function(p, location, scale, shape) {
  .Call(`_bestfitr_bf_gev_quantile_gradient_`, p, location, scale, shape)
}

bf_gev_parameter_covariance_ <- function(location, scale, shape, sample_size) {
  .Call(`_bestfitr_bf_gev_parameter_covariance_`, location, scale, shape, sample_size)
}

bf_mcmc_run_ <- function(sampler_type, model_name, family, dataset, settings) {
  .Call(`_bestfitr_bf_mcmc_run_`, sampler_type, model_name, family, dataset, settings)
}

bf_dirichlet_val_ <- function(method, alpha, args) {
  .Call(`_bestfitr_bf_dirichlet_val_`, method, alpha, args)
}

bf_multinomial_val_ <- function(method, n, p, args) {
  .Call(`_bestfitr_bf_multinomial_val_`, method, n, p, args)
}

bf_bve_cdf_ <- function(method, x1, x2, p_flat, nrow, transforms, args) {
  .Call(`_bestfitr_bf_bve_cdf_`, method, x1, x2, p_flat, nrow, transforms, args)
}

bf_mvn_val_ <- function(method, mean, cov_flat, args) {
  .Call(`_bestfitr_bf_mvn_val_`, method, mean, cov_flat, args)
}

bf_mvn_cdf_seq_ <- function(mean, cov_flat, seed, xs_flat, k) {
  .Call(`_bestfitr_bf_mvn_cdf_seq_`, mean, cov_flat, seed, xs_flat, k)
}

bf_mvn_interval_seq_ <- function(mean, cov_flat, seed, lowers_flat, uppers_flat, k) {
  .Call(`_bestfitr_bf_mvn_interval_seq_`, mean, cov_flat, seed, lowers_flat, uppers_flat, k)
}

bf_mvn_mvndst_seq_ <- function(n_dim, seed, lower_flat, upper_flat, infin_flat, correl_flat, maxpts_v, abseps_v, releps_v, k) {
  .Call(`_bestfitr_bf_mvn_mvndst_seq_`, n_dim, seed, lower_flat, upper_flat, infin_flat, correl_flat, maxpts_v, abseps_v, releps_v, k)
}

bf_mvt_val_ <- function(method, df, location, scale_flat, args) {
  .Call(`_bestfitr_bf_mvt_val_`, method, df, location, scale_flat, args)
}

bf_sobol_generate_ <- function(dimension, n_steps, path) {
  .Call(`_bestfitr_bf_sobol_generate_`, dimension, n_steps, path)
}

bf_sobol_skip_to_ <- function(dimension, index, path) {
  .Call(`_bestfitr_bf_sobol_skip_to_`, dimension, index, path)
}
