// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// bootstrap.cpp
list bf_bootstrap_run_(std::string model, double mu, double sigma, int sample_size, doubles probabilities, doubles dataset, int replicates, int seed, int max_retries, std::string run, std::string ci_method, double alpha);
extern "C" SEXP _bestfitr_bf_bootstrap_run_(SEXP model, SEXP mu, SEXP sigma, SEXP sample_size, SEXP probabilities, SEXP dataset, SEXP replicates, SEXP seed, SEXP max_retries, SEXP run, SEXP ci_method, SEXP alpha) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_bootstrap_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model), cpp11::as_cpp<cpp11::decay_t<double>>(mu), cpp11::as_cpp<cpp11::decay_t<double>>(sigma), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<doubles>>(probabilities), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<int>>(replicates), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(max_retries), cpp11::as_cpp<cpp11::decay_t<std::string>>(run), cpp11::as_cpp<cpp11::decay_t<std::string>>(ci_method), cpp11::as_cpp<cpp11::decay_t<double>>(alpha)));
  END_CPP11
}
// copula.cpp
double bf_cop_val_(std::string type, doubles params, std::string method, doubles args, std::string marg_x_target, doubles marg_x_params, std::string marg_y_target, doubles marg_y_params);
extern "C" SEXP _bestfitr_bf_cop_val_(SEXP type, SEXP params, SEXP method, SEXP args, SEXP marg_x_target, SEXP marg_x_params, SEXP marg_y_target, SEXP marg_y_params) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cop_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(args), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_x_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(marg_x_params), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_y_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(marg_y_params)));
  END_CPP11
}
// copula.cpp
list bf_cop_fit_(std::string type, doubles x, doubles y, std::string method, std::string marg_x, std::string marg_y);
extern "C" SEXP _bestfitr_bf_cop_fit_(SEXP type, SEXP x, SEXP y, SEXP method, SEXP marg_x, SEXP marg_y) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cop_fit_(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_x), cpp11::as_cpp<cpp11::decay_t<std::string>>(marg_y)));
  END_CPP11
}
// dist.cpp
doubles bf_dist_moments_(std::string target, doubles params);
extern "C" SEXP _bestfitr_bf_dist_moments_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_moments_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
double bf_dist_pdf_(std::string target, doubles params, double x);
extern "C" SEXP _bestfitr_bf_dist_pdf_(SEXP target, SEXP params, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_pdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_dist_cdf_(std::string target, doubles params, double x);
extern "C" SEXP _bestfitr_bf_dist_cdf_(SEXP target, SEXP params, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_cdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_dist_quantile_(std::string target, doubles params, double p);
extern "C" SEXP _bestfitr_bf_dist_quantile_(SEXP target, SEXP params, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_quantile_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params), cpp11::as_cpp<cpp11::decay_t<double>>(p)));
  END_CPP11
}
// dist.cpp
bool bf_dist_valid_(std::string target, doubles params);
extern "C" SEXP _bestfitr_bf_dist_valid_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_valid_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
doubles bf_dist_fit_(std::string target, doubles data, std::string method);
extern "C" SEXP _bestfitr_bf_dist_fit_(SEXP target, SEXP data, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_fit_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// dist.cpp
doubles bf_dist_linear_moments_(std::string target, doubles params);
extern "C" SEXP _bestfitr_bf_dist_linear_moments_(SEXP target, SEXP params) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dist_linear_moments_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<doubles>>(params)));
  END_CPP11
}
// dist.cpp
doubles bf_trunc_moments_(std::string base_target, doubles base_params, double lo, double hi);
extern "C" SEXP _bestfitr_bf_trunc_moments_(SEXP base_target, SEXP base_params, SEXP lo, SEXP hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_trunc_moments_(cpp11::as_cpp<cpp11::decay_t<std::string>>(base_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(base_params), cpp11::as_cpp<cpp11::decay_t<double>>(lo), cpp11::as_cpp<cpp11::decay_t<double>>(hi)));
  END_CPP11
}
// dist.cpp
double bf_trunc_pdf_(std::string base_target, doubles base_params, double lo, double hi, double x);
extern "C" SEXP _bestfitr_bf_trunc_pdf_(SEXP base_target, SEXP base_params, SEXP lo, SEXP hi, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_trunc_pdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(base_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(base_params), cpp11::as_cpp<cpp11::decay_t<double>>(lo), cpp11::as_cpp<cpp11::decay_t<double>>(hi), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_trunc_cdf_(std::string base_target, doubles base_params, double lo, double hi, double x);
extern "C" SEXP _bestfitr_bf_trunc_cdf_(SEXP base_target, SEXP base_params, SEXP lo, SEXP hi, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_trunc_cdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(base_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(base_params), cpp11::as_cpp<cpp11::decay_t<double>>(lo), cpp11::as_cpp<cpp11::decay_t<double>>(hi), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_trunc_quantile_(std::string base_target, doubles base_params, double lo, double hi, double p);
extern "C" SEXP _bestfitr_bf_trunc_quantile_(SEXP base_target, SEXP base_params, SEXP lo, SEXP hi, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_trunc_quantile_(cpp11::as_cpp<cpp11::decay_t<std::string>>(base_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(base_params), cpp11::as_cpp<cpp11::decay_t<double>>(lo), cpp11::as_cpp<cpp11::decay_t<double>>(hi), cpp11::as_cpp<cpp11::decay_t<double>>(p)));
  END_CPP11
}
// dist.cpp
bool bf_trunc_valid_(std::string base_target, doubles base_params, double lo, double hi);
extern "C" SEXP _bestfitr_bf_trunc_valid_(SEXP base_target, SEXP base_params, SEXP lo, SEXP hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_trunc_valid_(cpp11::as_cpp<cpp11::decay_t<std::string>>(base_target), cpp11::as_cpp<cpp11::decay_t<doubles>>(base_params), cpp11::as_cpp<cpp11::decay_t<double>>(lo), cpp11::as_cpp<cpp11::decay_t<double>>(hi)));
  END_CPP11
}
// dist.cpp
doubles bf_emp_moments_(doubles x_vals, doubles p_vals, std::string p_transform);
extern "C" SEXP _bestfitr_bf_emp_moments_(SEXP x_vals, SEXP p_vals, SEXP p_transform) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_emp_moments_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform)));
  END_CPP11
}
// dist.cpp
double bf_emp_pdf_(doubles x_vals, doubles p_vals, std::string p_transform, double x);
extern "C" SEXP _bestfitr_bf_emp_pdf_(SEXP x_vals, SEXP p_vals, SEXP p_transform, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_emp_pdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_emp_cdf_(doubles x_vals, doubles p_vals, std::string p_transform, double x);
extern "C" SEXP _bestfitr_bf_emp_cdf_(SEXP x_vals, SEXP p_vals, SEXP p_transform, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_emp_cdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_emp_quantile_(doubles x_vals, doubles p_vals, std::string p_transform, double prob);
extern "C" SEXP _bestfitr_bf_emp_quantile_(SEXP x_vals, SEXP p_vals, SEXP p_transform, SEXP prob) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_emp_quantile_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform), cpp11::as_cpp<cpp11::decay_t<double>>(prob)));
  END_CPP11
}
// dist.cpp
bool bf_emp_valid_(doubles x_vals, doubles p_vals, std::string p_transform);
extern "C" SEXP _bestfitr_bf_emp_valid_(SEXP x_vals, SEXP p_vals, SEXP p_transform) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_emp_valid_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x_vals), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_vals), cpp11::as_cpp<cpp11::decay_t<std::string>>(p_transform)));
  END_CPP11
}
// dist.cpp
doubles bf_kde_moments_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data);
extern "C" SEXP _bestfitr_bf_kde_moments_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_kde_moments_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data)));
  END_CPP11
}
// dist.cpp
double bf_kde_pdf_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data, double x);
extern "C" SEXP _bestfitr_bf_kde_pdf_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_kde_pdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_kde_cdf_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data, double x);
extern "C" SEXP _bestfitr_bf_kde_cdf_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_kde_cdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_kde_quantile_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data, double prob);
extern "C" SEXP _bestfitr_bf_kde_quantile_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data, SEXP prob) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_kde_quantile_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data), cpp11::as_cpp<cpp11::decay_t<double>>(prob)));
  END_CPP11
}
// dist.cpp
bool bf_kde_valid_(doubles data, std::string kernel, double bandwidth, bool bounded_by_data);
extern "C" SEXP _bestfitr_bf_kde_valid_(SEXP data, SEXP kernel, SEXP bandwidth, SEXP bounded_by_data) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_kde_valid_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(kernel), cpp11::as_cpp<cpp11::decay_t<double>>(bandwidth), cpp11::as_cpp<cpp11::decay_t<bool>>(bounded_by_data)));
  END_CPP11
}
// dist.cpp
doubles bf_mix_moments_(strings comp_targets, list comp_params_list, doubles weights);
extern "C" SEXP _bestfitr_bf_mix_moments_(SEXP comp_targets, SEXP comp_params_list, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mix_moments_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<doubles>>(weights)));
  END_CPP11
}
// dist.cpp
double bf_mix_pdf_(strings comp_targets, list comp_params_list, doubles weights, double x);
extern "C" SEXP _bestfitr_bf_mix_pdf_(SEXP comp_targets, SEXP comp_params_list, SEXP weights, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mix_pdf_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<doubles>>(weights), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_mix_cdf_(strings comp_targets, list comp_params_list, doubles weights, double x);
extern "C" SEXP _bestfitr_bf_mix_cdf_(SEXP comp_targets, SEXP comp_params_list, SEXP weights, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mix_cdf_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<doubles>>(weights), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_mix_quantile_(strings comp_targets, list comp_params_list, doubles weights, double prob);
extern "C" SEXP _bestfitr_bf_mix_quantile_(SEXP comp_targets, SEXP comp_params_list, SEXP weights, SEXP prob) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mix_quantile_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<doubles>>(weights), cpp11::as_cpp<cpp11::decay_t<double>>(prob)));
  END_CPP11
}
// dist.cpp
bool bf_mix_valid_(strings comp_targets, list comp_params_list, doubles weights);
extern "C" SEXP _bestfitr_bf_mix_valid_(SEXP comp_targets, SEXP comp_params_list, SEXP weights) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mix_valid_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<doubles>>(weights)));
  END_CPP11
}
// dist.cpp
doubles bf_cr_moments_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation);
extern "C" SEXP _bestfitr_bf_cr_moments_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_moments_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation)));
  END_CPP11
}
// dist.cpp
double bf_cr_pdf_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation, double x);
extern "C" SEXP _bestfitr_bf_cr_pdf_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_pdf_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_cr_log_pdf_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation, double x);
extern "C" SEXP _bestfitr_bf_cr_log_pdf_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_log_pdf_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_cr_cdf_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation, double x);
extern "C" SEXP _bestfitr_bf_cr_cdf_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_cdf_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// dist.cpp
double bf_cr_quantile_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation, double prob);
extern "C" SEXP _bestfitr_bf_cr_quantile_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation, SEXP prob) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_quantile_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation), cpp11::as_cpp<cpp11::decay_t<double>>(prob)));
  END_CPP11
}
// dist.cpp
bool bf_cr_valid_(strings comp_targets, list comp_params_list, bool minimum_of_rv, std::string dependency, list correlation);
extern "C" SEXP _bestfitr_bf_cr_valid_(SEXP comp_targets, SEXP comp_params_list, SEXP minimum_of_rv, SEXP dependency, SEXP correlation) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_cr_valid_(cpp11::as_cpp<cpp11::decay_t<strings>>(comp_targets), cpp11::as_cpp<cpp11::decay_t<list>>(comp_params_list), cpp11::as_cpp<cpp11::decay_t<bool>>(minimum_of_rv), cpp11::as_cpp<cpp11::decay_t<std::string>>(dependency), cpp11::as_cpp<cpp11::decay_t<list>>(correlation)));
  END_CPP11
}
// estimation.cpp
list bf_estimation_run_(std::string target, std::string model_json, doubles dataset, std::string optimizer);
extern "C" SEXP _bestfitr_bf_estimation_run_(SEXP target, SEXP model_json, SEXP dataset, SEXP optimizer) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_estimation_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer)));
  END_CPP11
}
// estimation.cpp
double bf_estimation_bic_(std::string target, std::string model_json, doubles dataset, std::string optimizer, int n);
extern "C" SEXP _bestfitr_bf_estimation_bic_(SEXP target, SEXP model_json, SEXP dataset, SEXP optimizer, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_estimation_bic_(cpp11::as_cpp<cpp11::decay_t<std::string>>(target), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// estimation.cpp
list bf_estimation_bayes_run_(std::string model_json, doubles dataset, std::string sampler, int seed, int iterations, int warmup_iterations, int number_of_chains, int thinning_interval, int initial_iterations, int output_length);
extern "C" SEXP _bestfitr_bf_estimation_bayes_run_(SEXP model_json, SEXP dataset, SEXP sampler, SEXP seed, SEXP iterations, SEXP warmup_iterations, SEXP number_of_chains, SEXP thinning_interval, SEXP initial_iterations, SEXP output_length) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_estimation_bayes_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(warmup_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(number_of_chains), cpp11::as_cpp<cpp11::decay_t<int>>(thinning_interval), cpp11::as_cpp<cpp11::decay_t<int>>(initial_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(output_length)));
  END_CPP11
}
// estimation.cpp
list bf_model_data_frame_(std::string model_json, doubles dataset);
extern "C" SEXP _bestfitr_bf_model_data_frame_(SEXP model_json, SEXP dataset) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_model_data_frame_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset)));
  END_CPP11
}
// estimation.cpp
doubles bf_model_simulate_(std::string model_json, doubles dataset, int sample_size, int seed);
extern "C" SEXP _bestfitr_bf_model_simulate_(SEXP model_json, SEXP dataset, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_model_simulate_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// estimation.cpp
list bf_estimation_gmm_run_(std::string model_json, doubles dataset, std::string strategy, std::string optimizer, int max_gmm_iterations, int sample_size, int seed);
extern "C" SEXP _bestfitr_bf_estimation_gmm_run_(SEXP model_json, SEXP dataset, SEXP strategy, SEXP optimizer, SEXP max_gmm_iterations, SEXP sample_size, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_estimation_gmm_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(strategy), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(max_gmm_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// estimation.cpp
double bf_estimation_gmm_qvar_(std::string model_json, doubles dataset, std::string strategy, std::string optimizer, int max_gmm_iterations, double aep);
extern "C" SEXP _bestfitr_bf_estimation_gmm_qvar_(SEXP model_json, SEXP dataset, SEXP strategy, SEXP optimizer, SEXP max_gmm_iterations, SEXP aep) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_estimation_gmm_qvar_(cpp11::as_cpp<cpp11::decay_t<std::string>>(model_json), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<std::string>>(strategy), cpp11::as_cpp<cpp11::decay_t<std::string>>(optimizer), cpp11::as_cpp<cpp11::decay_t<int>>(max_gmm_iterations), cpp11::as_cpp<cpp11::decay_t<double>>(aep)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_pdf_(doubles x, double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_pdf_(SEXP x, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_pdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_cdf_(doubles x, double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_cdf_(SEXP x, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_cdf_(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_quantile_(doubles p, double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_quantile_(SEXP p, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_quantile_(cpp11::as_cpp<cpp11::decay_t<doubles>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_moments_(double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_moments_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_moments_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
bool bf_gev_valid_(double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_valid_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_valid_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_fit_(doubles data, std::string method);
extern "C" SEXP _bestfitr_bf_gev_fit_(SEXP data, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_fit_(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// gev.cpp
double bf_gev_quantile_variance_(double p, double location, double scale, double shape, int sample_size);
extern "C" SEXP _bestfitr_bf_gev_quantile_variance_(SEXP p, SEXP location, SEXP scale, SEXP shape, SEXP sample_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_quantile_variance_(cpp11::as_cpp<cpp11::decay_t<double>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_linear_moments_(double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_linear_moments_(SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_linear_moments_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_quantile_gradient_(double p, double location, double scale, double shape);
extern "C" SEXP _bestfitr_bf_gev_quantile_gradient_(SEXP p, SEXP location, SEXP scale, SEXP shape) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_quantile_gradient_(cpp11::as_cpp<cpp11::decay_t<double>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape)));
  END_CPP11
}
// gev.cpp
doubles bf_gev_parameter_covariance_(double location, double scale, double shape, int sample_size);
extern "C" SEXP _bestfitr_bf_gev_parameter_covariance_(SEXP location, SEXP scale, SEXP shape, SEXP sample_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_gev_parameter_covariance_(cpp11::as_cpp<cpp11::decay_t<double>>(location), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(shape), cpp11::as_cpp<cpp11::decay_t<int>>(sample_size)));
  END_CPP11
}
// mcmc.cpp
list bf_mcmc_run_(std::string sampler_type, std::string model_name, std::string family, doubles dataset, list settings);
extern "C" SEXP _bestfitr_bf_mcmc_run_(SEXP sampler_type, SEXP model_name, SEXP family, SEXP dataset, SEXP settings) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mcmc_run_(cpp11::as_cpp<cpp11::decay_t<std::string>>(sampler_type), cpp11::as_cpp<cpp11::decay_t<std::string>>(model_name), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<doubles>>(dataset), cpp11::as_cpp<cpp11::decay_t<list>>(settings)));
  END_CPP11
}
// mvd.cpp
double bf_dirichlet_val_(std::string method, doubles alpha, doubles args);
extern "C" SEXP _bestfitr_bf_dirichlet_val_(SEXP method, SEXP alpha, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_dirichlet_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(alpha), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
double bf_multinomial_val_(std::string method, int n, doubles p, doubles args);
extern "C" SEXP _bestfitr_bf_multinomial_val_(SEXP method, SEXP n, SEXP p, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_multinomial_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<doubles>>(p), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
double bf_bve_cdf_(std::string method, doubles x1, doubles x2, doubles p_flat, int nrow, strings transforms, doubles args);
extern "C" SEXP _bestfitr_bf_bve_cdf_(SEXP method, SEXP x1, SEXP x2, SEXP p_flat, SEXP nrow, SEXP transforms, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_bve_cdf_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(x1), cpp11::as_cpp<cpp11::decay_t<doubles>>(x2), cpp11::as_cpp<cpp11::decay_t<doubles>>(p_flat), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<strings>>(transforms), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
double bf_mvn_val_(std::string method, doubles mean, doubles cov_flat, doubles args);
extern "C" SEXP _bestfitr_bf_mvn_val_(SEXP method, SEXP mean, SEXP cov_flat, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mvn_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<doubles>>(mean), cpp11::as_cpp<cpp11::decay_t<doubles>>(cov_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// mvd.cpp
doubles bf_mvn_cdf_seq_(doubles mean, doubles cov_flat, int seed, doubles xs_flat, int k);
extern "C" SEXP _bestfitr_bf_mvn_cdf_seq_(SEXP mean, SEXP cov_flat, SEXP seed, SEXP xs_flat, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mvn_cdf_seq_(cpp11::as_cpp<cpp11::decay_t<doubles>>(mean), cpp11::as_cpp<cpp11::decay_t<doubles>>(cov_flat), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(xs_flat), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// mvd.cpp
doubles bf_mvn_interval_seq_(doubles mean, doubles cov_flat, int seed, doubles lowers_flat, doubles uppers_flat, int k);
extern "C" SEXP _bestfitr_bf_mvn_interval_seq_(SEXP mean, SEXP cov_flat, SEXP seed, SEXP lowers_flat, SEXP uppers_flat, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mvn_interval_seq_(cpp11::as_cpp<cpp11::decay_t<doubles>>(mean), cpp11::as_cpp<cpp11::decay_t<doubles>>(cov_flat), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(lowers_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(uppers_flat), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// mvd.cpp
doubles bf_mvn_mvndst_seq_(int n_dim, int seed, doubles lower_flat, doubles upper_flat, integers infin_flat, doubles correl_flat, integers maxpts_v, doubles abseps_v, doubles releps_v, int k);
extern "C" SEXP _bestfitr_bf_mvn_mvndst_seq_(SEXP n_dim, SEXP seed, SEXP lower_flat, SEXP upper_flat, SEXP infin_flat, SEXP correl_flat, SEXP maxpts_v, SEXP abseps_v, SEXP releps_v, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mvn_mvndst_seq_(cpp11::as_cpp<cpp11::decay_t<int>>(n_dim), cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<doubles>>(lower_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(upper_flat), cpp11::as_cpp<cpp11::decay_t<integers>>(infin_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(correl_flat), cpp11::as_cpp<cpp11::decay_t<integers>>(maxpts_v), cpp11::as_cpp<cpp11::decay_t<doubles>>(abseps_v), cpp11::as_cpp<cpp11::decay_t<doubles>>(releps_v), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// mvd.cpp
double bf_mvt_val_(std::string method, double df, doubles location, doubles scale_flat, doubles args);
extern "C" SEXP _bestfitr_bf_mvt_val_(SEXP method, SEXP df, SEXP location, SEXP scale_flat, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_mvt_val_(cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(df), cpp11::as_cpp<cpp11::decay_t<doubles>>(location), cpp11::as_cpp<cpp11::decay_t<doubles>>(scale_flat), cpp11::as_cpp<cpp11::decay_t<doubles>>(args)));
  END_CPP11
}
// sobol.cpp
doubles_matrix<by_column> bf_sobol_generate_(int dimension, int n_steps, std::string path);
extern "C" SEXP _bestfitr_bf_sobol_generate_(SEXP dimension, SEXP n_steps, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_sobol_generate_(cpp11::as_cpp<cpp11::decay_t<int>>(dimension), cpp11::as_cpp<cpp11::decay_t<int>>(n_steps), cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// sobol.cpp
doubles bf_sobol_skip_to_(int dimension, int index, std::string path);
extern "C" SEXP _bestfitr_bf_sobol_skip_to_(SEXP dimension, SEXP index, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(bf_sobol_skip_to_(cpp11::as_cpp<cpp11::decay_t<int>>(dimension), cpp11::as_cpp<cpp11::decay_t<int>>(index), cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_bestfitr_bf_bootstrap_run_",            (DL_FUNC) &_bestfitr_bf_bootstrap_run_,            12},
    {"_bestfitr_bf_bve_cdf_",                  (DL_FUNC) &_bestfitr_bf_bve_cdf_,                   7},
    {"_bestfitr_bf_cop_fit_",                  (DL_FUNC) &_bestfitr_bf_cop_fit_,                   6},
    {"_bestfitr_bf_cop_val_",                  (DL_FUNC) &_bestfitr_bf_cop_val_,                   8},
    {"_bestfitr_bf_cr_cdf_",                   (DL_FUNC) &_bestfitr_bf_cr_cdf_,                    6},
    {"_bestfitr_bf_cr_log_pdf_",               (DL_FUNC) &_bestfitr_bf_cr_log_pdf_,                6},
    {"_bestfitr_bf_cr_moments_",               (DL_FUNC) &_bestfitr_bf_cr_moments_,                5},
    {"_bestfitr_bf_cr_pdf_",                   (DL_FUNC) &_bestfitr_bf_cr_pdf_,                    6},
    {"_bestfitr_bf_cr_quantile_",              (DL_FUNC) &_bestfitr_bf_cr_quantile_,               6},
    {"_bestfitr_bf_cr_valid_",                 (DL_FUNC) &_bestfitr_bf_cr_valid_,                  5},
    {"_bestfitr_bf_dirichlet_val_",            (DL_FUNC) &_bestfitr_bf_dirichlet_val_,             3},
    {"_bestfitr_bf_dist_cdf_",                 (DL_FUNC) &_bestfitr_bf_dist_cdf_,                  3},
    {"_bestfitr_bf_dist_fit_",                 (DL_FUNC) &_bestfitr_bf_dist_fit_,                  3},
    {"_bestfitr_bf_dist_linear_moments_",      (DL_FUNC) &_bestfitr_bf_dist_linear_moments_,       2},
    {"_bestfitr_bf_dist_moments_",             (DL_FUNC) &_bestfitr_bf_dist_moments_,              2},
    {"_bestfitr_bf_dist_pdf_",                 (DL_FUNC) &_bestfitr_bf_dist_pdf_,                  3},
    {"_bestfitr_bf_dist_quantile_",            (DL_FUNC) &_bestfitr_bf_dist_quantile_,             3},
    {"_bestfitr_bf_dist_valid_",               (DL_FUNC) &_bestfitr_bf_dist_valid_,                2},
    {"_bestfitr_bf_emp_cdf_",                  (DL_FUNC) &_bestfitr_bf_emp_cdf_,                   4},
    {"_bestfitr_bf_emp_moments_",              (DL_FUNC) &_bestfitr_bf_emp_moments_,               3},
    {"_bestfitr_bf_emp_pdf_",                  (DL_FUNC) &_bestfitr_bf_emp_pdf_,                   4},
    {"_bestfitr_bf_emp_quantile_",             (DL_FUNC) &_bestfitr_bf_emp_quantile_,              4},
    {"_bestfitr_bf_emp_valid_",                (DL_FUNC) &_bestfitr_bf_emp_valid_,                 3},
    {"_bestfitr_bf_estimation_bayes_run_",     (DL_FUNC) &_bestfitr_bf_estimation_bayes_run_,     10},
    {"_bestfitr_bf_estimation_bic_",           (DL_FUNC) &_bestfitr_bf_estimation_bic_,            5},
    {"_bestfitr_bf_estimation_gmm_qvar_",      (DL_FUNC) &_bestfitr_bf_estimation_gmm_qvar_,       6},
    {"_bestfitr_bf_estimation_gmm_run_",       (DL_FUNC) &_bestfitr_bf_estimation_gmm_run_,        7},
    {"_bestfitr_bf_estimation_run_",           (DL_FUNC) &_bestfitr_bf_estimation_run_,            4},
    {"_bestfitr_bf_gev_cdf_",                  (DL_FUNC) &_bestfitr_bf_gev_cdf_,                   4},
    {"_bestfitr_bf_gev_fit_",                  (DL_FUNC) &_bestfitr_bf_gev_fit_,                   2},
    {"_bestfitr_bf_gev_linear_moments_",       (DL_FUNC) &_bestfitr_bf_gev_linear_moments_,        3},
    {"_bestfitr_bf_gev_moments_",              (DL_FUNC) &_bestfitr_bf_gev_moments_,               3},
    {"_bestfitr_bf_gev_parameter_covariance_", (DL_FUNC) &_bestfitr_bf_gev_parameter_covariance_,  4},
    {"_bestfitr_bf_gev_pdf_",                  (DL_FUNC) &_bestfitr_bf_gev_pdf_,                   4},
    {"_bestfitr_bf_gev_quantile_",             (DL_FUNC) &_bestfitr_bf_gev_quantile_,              4},
    {"_bestfitr_bf_gev_quantile_gradient_",    (DL_FUNC) &_bestfitr_bf_gev_quantile_gradient_,     4},
    {"_bestfitr_bf_gev_quantile_variance_",    (DL_FUNC) &_bestfitr_bf_gev_quantile_variance_,     5},
    {"_bestfitr_bf_gev_valid_",                (DL_FUNC) &_bestfitr_bf_gev_valid_,                 3},
    {"_bestfitr_bf_kde_cdf_",                  (DL_FUNC) &_bestfitr_bf_kde_cdf_,                   5},
    {"_bestfitr_bf_kde_moments_",              (DL_FUNC) &_bestfitr_bf_kde_moments_,               4},
    {"_bestfitr_bf_kde_pdf_",                  (DL_FUNC) &_bestfitr_bf_kde_pdf_,                   5},
    {"_bestfitr_bf_kde_quantile_",             (DL_FUNC) &_bestfitr_bf_kde_quantile_,              5},
    {"_bestfitr_bf_kde_valid_",                (DL_FUNC) &_bestfitr_bf_kde_valid_,                 4},
    {"_bestfitr_bf_mcmc_run_",                 (DL_FUNC) &_bestfitr_bf_mcmc_run_,                  5},
    {"_bestfitr_bf_mix_cdf_",                  (DL_FUNC) &_bestfitr_bf_mix_cdf_,                   4},
    {"_bestfitr_bf_mix_moments_",              (DL_FUNC) &_bestfitr_bf_mix_moments_,               3},
    {"_bestfitr_bf_mix_pdf_",                  (DL_FUNC) &_bestfitr_bf_mix_pdf_,                   4},
    {"_bestfitr_bf_mix_quantile_",             (DL_FUNC) &_bestfitr_bf_mix_quantile_,              4},
    {"_bestfitr_bf_mix_valid_",                (DL_FUNC) &_bestfitr_bf_mix_valid_,                 3},
    {"_bestfitr_bf_model_data_frame_",         (DL_FUNC) &_bestfitr_bf_model_data_frame_,          2},
    {"_bestfitr_bf_model_simulate_",           (DL_FUNC) &_bestfitr_bf_model_simulate_,            4},
    {"_bestfitr_bf_multinomial_val_",          (DL_FUNC) &_bestfitr_bf_multinomial_val_,           4},
    {"_bestfitr_bf_mvn_cdf_seq_",              (DL_FUNC) &_bestfitr_bf_mvn_cdf_seq_,               5},
    {"_bestfitr_bf_mvn_interval_seq_",         (DL_FUNC) &_bestfitr_bf_mvn_interval_seq_,          6},
    {"_bestfitr_bf_mvn_mvndst_seq_",           (DL_FUNC) &_bestfitr_bf_mvn_mvndst_seq_,           10},
    {"_bestfitr_bf_mvn_val_",                  (DL_FUNC) &_bestfitr_bf_mvn_val_,                   4},
    {"_bestfitr_bf_mvt_val_",                  (DL_FUNC) &_bestfitr_bf_mvt_val_,                   5},
    {"_bestfitr_bf_sobol_generate_",           (DL_FUNC) &_bestfitr_bf_sobol_generate_,            3},
    {"_bestfitr_bf_sobol_skip_to_",            (DL_FUNC) &_bestfitr_bf_sobol_skip_to_,             3},
    {"_bestfitr_bf_trunc_cdf_",                (DL_FUNC) &_bestfitr_bf_trunc_cdf_,                 5},
    {"_bestfitr_bf_trunc_moments_",            (DL_FUNC) &_bestfitr_bf_trunc_moments_,             4},
    {"_bestfitr_bf_trunc_pdf_",                (DL_FUNC) &_bestfitr_bf_trunc_pdf_,                 5},
    {"_bestfitr_bf_trunc_quantile_",           (DL_FUNC) &_bestfitr_bf_trunc_quantile_,            5},
    {"_bestfitr_bf_trunc_valid_",              (DL_FUNC) &_bestfitr_bf_trunc_valid_,               4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_bestfitr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
